# Generated by Django 3.1.6 on 2021-02-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('email', models.CharField(max_length=140)),
                ('major', models.CharField(max_length=140)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=140)),
                ('drink', models.BooleanField()),
                ('attractedto', models.CharField(max_length=140)),
                ('distance_campus', models.CharField(max_length=140)),
                ('politics', models.CharField(max_length=140)),
                ('religion', models.CharField(max_length=140)),
                ('sharereligion', models.CharField(max_length=140)),
                ('social', models.CharField(max_length=140)),
                ('party', models.CharField(max_length=140)),
                ('pastmatches', models.CharField(max_length=64000)),
            ],
        ),
    ]
